public class ImplimentationofInterfaces Implements MyInterface1,MyInterface2 {
    public void info(){
        System.debug('Info method in Implementation of Interfaces class');
    }
    
    public void infoInterface1(){
        System.debug('Implementation of infoInterface1 method in its child class');
    }
    
    public void infoInterface2(){
        System.debug('Implementation of infoInterface2 method in its child class');
    }
}